# Generated by Django 4.0.3 on 2022-06-20 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=100, verbose_name='키워드')),
            ],
            options={
                'db_table': 'kodeal_keyword',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='질문 내용')),
                ('language', models.CharField(blank=True, max_length=30, null=True, verbose_name='사용 언어')),
                ('create_date', models.DateTimeField(verbose_name='생성일')),
                ('modify_date', models.DateTimeField(blank=True, null=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_q', to=settings.AUTH_USER_MODEL, verbose_name='질문 작성자')),
                ('keyword', models.ManyToManyField(related_name='keyword_q', to='kodeal.keyword', verbose_name='키워드')),
                ('voter', models.ManyToManyField(related_name='voter_q', to=settings.AUTH_USER_MODEL, verbose_name='추천인')),
            ],
            options={
                'db_table': 'kodeal_codex_question',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='이미지')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_owner', to=settings.AUTH_USER_MODEL, verbose_name='이미지 소유자')),
            ],
            options={
                'db_table': 'kodeal_profile',
            },
        ),
        migrations.CreateModel(
            name='Papago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='번역 결과')),
                ('create_date', models.DateTimeField(verbose_name='생성일')),
                ('modify_date', models.DateTimeField(blank=True, null=True, verbose_name='수정일')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodeal.question', verbose_name='연관된 질문')),
            ],
            options={
                'db_table': 'kodeal_papago',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='답변 결과')),
                ('create_date', models.DateTimeField(verbose_name='생성일')),
                ('modify_date', models.DateTimeField(blank=True, null=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_a', to=settings.AUTH_USER_MODEL, verbose_name='답변 작성자')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodeal.question', verbose_name='연관된 질문')),
                ('voter', models.ManyToManyField(related_name='voter_a', to=settings.AUTH_USER_MODEL, verbose_name='추천인')),
            ],
            options={
                'db_table': 'kodeal_codex_answer',
            },
        ),
    ]
