# Generated by Django 4.0.3 on 2022-06-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodeal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='language',
            field=models.CharField(default=1, max_length=30, verbose_name='사용 언어'),
            preserve_default=False,
        ),
    ]
