# Generated by Django 4.0.4 on 2022-06-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodeal', '0003_remove_question_keyword_keyword_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papago',
            name='content',
        ),
        migrations.AddField(
            model_name='papago',
            name='after_question',
            field=models.TextField(default=1, verbose_name='번역 전'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='papago',
            name='before_question',
            field=models.TextField(default=1, verbose_name='번역 전'),
            preserve_default=False,
        ),
    ]
