# Generated by Django 4.0.4 on 2022-06-21 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kodeal', '0004_remove_papago_content_papago_after_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='코멘트 내용')),
                ('create_date', models.DateTimeField(verbose_name='생성일')),
                ('modify_date', models.DateTimeField(blank=True, null=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_q', to=settings.AUTH_USER_MODEL, verbose_name='코멘트 작성자')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodeal.question', verbose_name='연관된 질문')),
            ],
        ),
    ]
