# Generated by Django 4.0.4 on 2022-06-21 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kodeal', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer',
            table='kodeal_answer',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='kodeal_comment',
        ),
        migrations.AlterModelTable(
            name='question',
            table='kodeal_question',
        ),
    ]
