# Generated by Django 4.0.4 on 2022-06-21 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kodeal', '0006_alter_answer_table_alter_comment_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='voter',
            field=models.ManyToManyField(related_name='voter_c', to=settings.AUTH_USER_MODEL, verbose_name='추천인'),
        ),
    ]
